sudo: false
language: ruby

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head
  - jruby-9.1.9.0
  - jruby-head
  
matrix:
  allow_failures:
    - rvm: 2.6.0
    - rvm: ruby-head
    - rvm: jruby-head

 before_install:
  - gem update --system
  - gem install bundler

# whitelist
branches:
  only:
    - master
